[package]
name = "windowing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
wgpu = { git = "https://github.com/gfx-rs/wgpu" }
pollster = "*"
